version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:14.2-alpine
    container_name: nbdc-docker-pg
    ports:
      - 5432:5432
    networks:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    command: ['postgres', '-c', 'log_statement=all', '-c', 'log_destination=stderr']
    volumes:
      - pgvol:/var/lib/postgresql/data:delegated
  next-js:
    # Install dependencies only when needed
    build: .
    volumes:
      - nextjsvol:/var/lib/nextjsvol/data:delegated
    ports:
      - 3000:3000
    networks:
      - postgres
volumes:
  pgvol:
  nextjsvol:

networks:
  postgres:
    name: postgres
