name: Run All Tests
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn
      - name: Lint project
        run: npm run lint
      # TODO: fix playwright tests and add back into gh actions
      # - name: Install Playwright
      #   run: npx playwright install --with-deps
      - name: Run Jest
        run: npm run test:unit
      # - name: Run Playwright tests
      #   run: npm run test:e2e
